apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.spec.appName }}"
  namespace: "{{ .Values.spec.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.spec.appName }}"
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
